apiVersion: batch/v1
kind: Job
metadata:
  name: common-services-services
spec:
  template:
    metadata:
      name: common-services-services-pod
    spec:
      containers:
        - name: common-services-services
          image: hpid-service-common-services:latest
          imagePullPolicy: Never
      restartPolicy: Never