# Use a base image with JDK 17 and Maven pre-installed
FROM maven:3.8.3-amazoncorretto-17 as build
WORKDIR /app
COPY . .
#RUN mvn install -DskipTests
# Inject the JAR file into a new container to keep the file small
FROM openjdk:17
WORKDIR /app
COPY --from=build /app/target/*.jar /app/app.jar
EXPOSE 9002
ENTRYPOINT ["sh", "-c"]
CMD ["java -jar app.jar"]