apiVersion: batch/v1
kind: Job
metadata:
  name: transaction-services
spec:
  template:
    metadata:
      name: transaction-services-pod
    spec:
      containers:
        - name: transaction-services
          image: hpid-service-transaction-services:latest
          imagePullPolicy: Never
      restartPolicy: Never